### ISSUE TITLE
HTTP load failed (error code: -999)

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [rwbutler/Connectivity#11] opened 2019-02-05 08:29 UTC
always appear above message in log of my project, and sometimes cause my app to crash.

**Comment by BurierAbdalwahhabElia** [comment] 2019-02-05 11:35
when app reach to the last line, crash

**2019-01-21 11:25:34.711392+0300 ReservationOfOperationsHall[4628:795521]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2019-01-21 11:25:34.891998+0300 ReservationOfOperationsHall[4628:795480] [MC] Loaded MobileCoreServices.framework
2019-01-21 11:25:34.981826+0300 ReservationOfOperationsHall[4628:795521] 5.10.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50200000 started
2019-01-21 11:25:34.981999+0300 ReservationOfOperationsHall[4628:795521] 5.10.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2019-01-21 11:25:35.018005+0300 ReservationOfOperationsHall[4628:795480] refreshPreferences: HangTracerEnabled: 0
2019-01-21 11:25:35.018369+0300 ReservationOfOperationsHall[4628:795480] refreshPreferences: HangTracerDuration: 500
2019-01-21 11:25:35.018643+0300 ReservationOfOperationsHall[4628:795480] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
2019-01-21 11:25:35.174202+0300 ReservationOfOperationsHall[4628:795521] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2019-01-21 11:25:35.387850+0300 ReservationOfOperationsHall[4628:795533] TIC Read Status [1:0x0]: 1:57
2019-01-21 11:25:35.387878+0300 ReservationOfOperationsHall[4628:795533] TIC Read Status [1:0x0]: 1:57
2019-01-21 11:25:40.086944+0300 ReservationOfOperationsHall[4628:795531] TIC Read Status [3:0x1c017d340]: 1:57
2019-01-21 11:25:40.197949+0300 ReservationOfOperationsHall[4628:795480] Reachability Flag Status: -R ------- networkStatusForFlags
2019-01-21 11:25:40.198039+0300 ReservationOfOperationsHall[4628:795480] Reachability Flag Status: -R ------- networkStatusForFlags
2019-01-21 11:25:40.198136+0300 ReservationOfOperationsHall[4628:795526] Task <1AA895E9-0115-4D4F-97A1-9DA228C888ED>.<2> HTTP load failed (error code: -999 [1:89])
Internet
2019-01-21 11:25:40.198321+0300 ReservationOfOperationsHall[4628:795531] Task <1AA895E9-0115-4D4F-97A1-9DA228C888ED>.<2> finished with error - code: -999
usserrrrrrrrrrrrrrOptional("ali3@nhs.iq")verified
loaded again
iPhone 6+/6S+/7+/8+
user id Optional("y4ZwPvmTJ7U0c2V2Xw9w84zTyao2")
2019-01-21 11:25:40.287908+0300 ReservationOfOperationsHall[4628:795480] Reachability Flag Status: -R ------- networkStatusForFlags
2019-01-21 11:25:40.647583+0300 ReservationOfOperationsHall[4628:795531] TIC Read Status [11:0x1c417ef00]: 1:57
2019-01-21 11:25:40.755796+0300 ReservationOfOperationsHall[4628:795480] Reachability Flag Status: -R ------- networkStatusForFlags
2019-01-21 11:25:40.755919+0300 ReservationOfOperationsHall[4628:795480] Reachability Flag Status: -R ------- networkStatusForFlags
2019-01-21 11:25:40.756412+0300 ReservationOfOperationsHall[4628:795526] Task <65027ED9-CDBA-48DC-8676-D7322CE6D15B>.<2> HTTP load failed (error code: -999 [1:89])
2019-01-21 11:25:40.756926+0300 ReservationOfOperationsHall[4628:795522] Task <65027ED9-CDBA-48DC-8676-D7322CE6D15B>.<2> finished with error - code: -999**

**Comment by rwbutler** [comment] 2019-02-05 12:13
Thanks for sending that over - that looks like the console log rather than an actual stack trace after a crash has occurred? Unfortunately there's nothing obvious that points towards a crash in your log but you may be able to get the crash trace out of Firebase as it looks as though you are using that or by copying and pasting after the crash has taken place.

**Comment by rwbutler** [comment] 2019-02-08 11:31
I'm going to go ahead and close this one for now because I haven't seen anything that points towards Connectivity as being the cause of a crash however if you find the crash stack trace and it points to the library then do let me know and I'll happily re-open.

**Closed by rwbutler** 2019-02-08 11:31 UTC
