### ISSUE TITLE
Crash in Xcode 15

### ISSUE THREAD

**Issue by mithunX89** [rwbutler/Connectivity#81] opened 2023-10-27 07:28 UTC
**Have read the known issues? **
[ ] Yes, I have read and am familiar with the list of [known issues](https://github.com/rwbutler/Connectivity#known-issues).

**Have tested on a physical device? **
[ ] Yes, I have tested on physical iOS device and the reported issue is still present.

**Does code retain the `Connectivity` object? **
[ ] Yes, my implementation has a strong reference to the `Connectivity` object so that it is not deallocated during use.

**Describe the bug**
Application is crashing on device when **_connectivity.checkConnectivity {}_** or _**connectivity.startNotifier()**_ is called in AppDelegate. This is occurring when running/archiving from **Xcode 15/15.1** beta versions. This is working without any issues on simulator and was working fine before when running/archiving from **Xcode 14.2/14.3.1.**

**To Reproduce**
1. Call connectivity.checkConnectivity {} or connectivity.startNotifier() in didFinishLaunchingWithOptions (AppDelegate.m)
2. Application crashes
3. Application works fine when both calls are removed

**Smartphone (please complete the following information):**
 - Device: [iPhone 6 Plus] [iPad mini 5th Generation]
 - OS: [iOS 12.6] [iPad OS 16.6]
 - Version [6.0.0] [6.1.1]

**Additional context**
This seems to be a problem when build/archiving from Xcode 15/later versions and Xcode 14.3.1 works fine.

**Comment by sekny** [comment] 2023-10-30 04:19
I got the same issue on Xcode 15 with Minimum Deployment Target 12

**Comment by AusCryptor82** [comment] 2023-11-01 22:14
Physical device crashes on Connectivity.startNotifier but works fine in simulators (XCode 15.0.1 and minimum deployment Target of 13)

**Comment by hugang1102** [comment] 2023-11-09 02:00
NWPathMonitor EXC_BAD_ACCESS, hope fix it

**Comment by sekny** [comment] 2023-11-13 01:29
> NWPathMonitor EXC_BAD_ACCESS, hope fix it

What's that for @hugang1102

**Comment by sekny** [comment] 2023-11-13 02:47
I found that the issue is related to XCode 15 itself not with library, so in my case, it fixed by change deployment target in Pod file to 12

`post_install do |installer|
	installer.generated_projects.each do |project|
		project.targets.each do |target|
				target.build_configurations.each do |config|
					config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"  # If using Apple silicon
					if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
						config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
					end
				end
		end
	end
end`

**Comment by hugang1102** [comment] 2023-11-14 03:18
> I found that the issue is related to XCode 15 itself not with library, so in my case, it fixed by change deployment target in Pod file to 12
> 
> ```
> post_install do |installer|
> 	installer.generated_projects.each do |project|
> 		project.targets.each do |target|
> 				target.build_configurations.each do |config|
> 					config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"  # If using Apple silicon
> 					if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
> 						config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
> 					end
> 				end
> 		end
> 	end
> end
> ```

crash in startPathMonitorNotifier

**Comment by sekny** [comment] 2023-11-17 01:44
> > I found that the issue is related to XCode 15 itself not with library, so in my case, it fixed by change deployment target in Pod file to 12
> > ```
> > post_install do |installer|
> > 	installer.generated_projects.each do |project|
> > 		project.targets.each do |target|
> > 				target.build_configurations.each do |config|
> > 					config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"  # If using Apple silicon
> > 					if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
> > 						config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
> > 					end
> > 				end
> > 		end
> > 	end
> > end
> > ```
> 
> crash in startPathMonitorNotifier

run `pod deintegrate` and `pod install` again

**Comment by abinhho** [comment] 2024-07-15 07:29
Same. 100% crashing on iOS 16 and XCode 15.3

**Comment by rwbutler** [comment] 2024-10-15 14:09
@abinhho @sekny @hugang1102 @AusCryptor82 @mithunX89 I've now updated the project for Xcode 16. Could you confirm whether you experience this or not in version 8.0.0?

**Comment by rwbutler** [comment] 2024-10-28 14:11
Closing for now as this no longer appears to be reproducible

**Closed by rwbutler** 2024-10-28 14:11 UTC
Labels: bug
