### ISSUE TITLE
Crash in Connectivity.startPathMonitorNotifier()

### ISSUE THREAD

**Issue by fassko** [rwbutler/Connectivity#22] opened 2019-08-01 09:25 UTC
My app is crashing and later in Firebase Crashlytics I found out this:
````
	Connectivity  0x1007a3f6c outlined assign with take of Any? (<compiler-generated>)
	Connectivity  0x1007a1984 closure #1 in Connectivity.startPathMonitorNotifier() + 257 (Connectivity.swift:257)
````

So it seems that there is an issue with setting path:
`self?.path = path`

**Comment by rwbutler** [comment] 2019-08-01 10:57
Unfortunately the compiler output for this error isn't very clear which makes it difficult to determine the precise issue but I'm working under the assumption that the issue is with the `#canImport` around the `path` property. I've removed this in version 3.0.3 which I'm hoping should resolve the issue for you.

If possible, could you let me know whether you're using Cococapods, Carthage or Swift  PM (and if using Carthage, the settings used to compile framework)?

**Comment by fassko** [comment] 2019-08-01 11:00
@rwbutler 

Rest of the crash report is this if this does help.

````
	Crashed: com.apple.root.background-qos
	0  libswiftCore.dylib             0x20710ac5c _swift_release_dealloc + 16
	1  libswiftNetwork.dylib          0x2073d01f0 destroy for NWPath + 28
	2  libswiftNetwork.dylib          0x2073d01f0 destroy for NWPath + 28
	3  libswiftCore.dylib             0x20710b88c (anonymous namespace)::destroyGenericBox(swift::HeapObject*) + 40
	4  libswiftCore.dylib             0x20710ac68 _swift_release_dealloc + 28
	5  Connectivity                   0x1007a3f6c outlined assign with take of Any? (<compiler-generated>)
	6  Connectivity                   0x1007a1984 closure #1 in Connectivity.startPathMonitorNotifier() + 257 (Connectivity.swift:257)
	7  libswiftNetwork.dylib          0x2073cd94c partial apply for closure #1 in NWPathMonitor.init(requiredInterfaceType:) + 76
	8  libswiftNetwork.dylib          0x2073bbdd8 thunk for @escaping @callee_guaranteed (@guaranteed OS_nw_path) -> () + 44
	9  libnetwork.dylib               0x1e90d9060 __nw_path_evaluator_call_update_handler_block_invoke + 64
	10 libdispatch.dylib              0x1e792979c _dispatch_call_block_and_release + 24
	11 libdispatch.dylib              0x1e792ad20 _dispatch_client_callout + 16
	12 libdispatch.dylib              0x1e7939d60 _dispatch_root_queue_drain + 676
	13 libdispatch.dylib              0x1e793a4c4 _dispatch_worker_thread2 + 128
	14 libsystem_pthread.dylib        0x1e7b3d818 _pthread_wqthread + 464
	15 libsystem_pthread.dylib        0x1e7b43b6c start_wqthread + 4
````

I'm using Cocoapods.

Maybe splitting out Network.framework stuff would be wiser idea, at least then no need to erase type for `path` property. What do you think?

**Comment by fassko** [comment] 2019-08-01 12:24
I upgraded to new version and will monitor how it is working. Thanks for this library! :)

**Comment by rwbutler** [comment] 2019-08-01 12:54
Thanks for the additional information and no problem 👍🏻 I have considered splitting this out into a separate Cocoapod (without Reachability / Obj-C) in the past for people who don't need to support older versions of iOS and don't want any Obj-C in their codebase - I may do so if there is a demand for it. I think I've discovered the true cause of the issue now so I'll need to produce another fix for this - hopefully I'll have this for you by the end of the day.

**Comment by rwbutler** [comment] 2019-08-01 16:33
After a bit of digging I think the real issue was caused by access to the `path` property not being thread-safe. I've added a little code in 3.0.4 to try to ensure that when the `path` property is updated it is done in a thread-safe manner. I think this should resolve the issue 👍🏻

**Comment by avitruk** [comment] 2019-08-06 13:52
Hi, I also have a crash with NWPath when trying to get current Connectivity.status via its getter.

![stacktrace](https://image.prntscr.com/image/Edr5oqiPSYS8NG0TFDN98Q.png)

Version: 3.0.4 / cocoapods
Any advices?

**Comment by rwbutler** [comment] 2019-08-06 13:59
Hi avitruk, could I just confirm that the version you are using is actually 3.0.4 (the version which was published 5 days ago)? Do you have an app in the App Store from which you are receiving this crash report?

**Comment by avitruk** [comment] 2019-08-06 14:02
@rwbutler this crash report is from internal testing on hockey app, and yes, the version is actually 3.0.4

**Comment by rwbutler** [comment] 2019-08-06 14:11
OK thanks for confirming. In the meantime in that case I would suggest using:

```
.framework = .systemConfiguration
```

for now since this issue is limited to those using the `Network` framework.

**Comment by avitruk** [comment] 2019-08-06 14:22
rwbutler, ok, thank you!
Also, maybe it makes sense to change Connectivity.status form computed property to stored property? You can update this property internally by notification and with this approach, we will not trigger NWPath properties/methods manually from an external source.

**Comment by rwbutler** [comment] 2019-08-06 14:41
Sounds like a good suggestion - I'll try to produce an update soon 👍🏻

**Comment by rwbutler** [comment] 2019-08-08 19:12
I've refactored a significant portion of library now so that the `status` property is stored rather than computed (version 3.1.0). With any luck this should resolve the crash you were experiencing🤞🏻

**Comment by avitruk** [comment] 2019-08-08 19:16
thanks) I will test this update soon :)

**Comment by patburns** [comment] 2019-08-09 03:26
I have almost the same exact stack as the one above. It's nice to find the fix is already in progress. Thanks for the library!

**Comment by rwbutler** [comment] 2019-08-10 16:18
No problem - hope this updates resolves the issue!

**Comment by fassko** [comment] 2019-08-12 07:11
Thanks @rwbutler I updated my app as well and will check if it has any issues!

**Closed** 2019-09-24 11:27 UTC
